name: test_leap_dataset
dependencies:
  - python=3.9
  - ipykernel
  - fsspec
  - gcsfs
  - pandas
  - xarray
  - apache-beam-with-gcp=2.42.0
  - pip
  - pip:
    - git+https://github.com/pangeo-forge/pangeo-forge-recipes.git@beam-refactor
    # manually install this one with --no-deps
    - git+https://github.com/pangeo-forge/pangeo-forge-runner.git@arbitrary-injections