name: test_leap_dataset
dependencies:
  - python=3.9
  - ipykernel
  - fsspec
  - gcsfs
  - pandas
  - xarray
  - gcsfs
  # - apache-beam-with-gcp=2.42.0
  - pip
  - pip:
    - git+https://github.com/pangeo-forge/pangeo-forge-recipes.git@beam-refactor
    - apache-beam[gcp]=2.42.0
    - git+https://github.com/pangeo-forge/pangeo-forge-runner.git