name: test_leap_dataset
dependencies:
  - python=3.9
  - ipykernel
  - fsspec
  - gcsfs
  - pandas
  - xarray
  - pip
  - pip:
    - apache-beam[gcp,interactive,dataframe]
    - git+https://github.com/pangeo-forge/pangeo-forge-recipes.git@beam-refactor
    - pangeo-forge-runner